name: Test Auction Arbitrage Bot

on: [push]

jobs:
  test:
    name: python test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: python -m pytest tests
      - name: Check src mypy
        run: MYPYPATH=src:build/gen mypy src --install-types --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs --strict
      - name: Check tests mypy
        run: MYPYPATH=src:build/gen mypy tests --install-types --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs --strict
      - name: Check main mypy
        run: MYPYPATH=src:build/gen mypy main.py --install-types --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs --strict
      - name: Check linter
        run: ruff check src
      - name: Check linter tests
        run: ruff check tests
      - name: Check linter main
        run: ruff check main.py
      - name: Check linter (pylint)
        run: PYTHONPATH=src:build/gen python -m pylint src
      - name: PYTHONPATH=src:build/gen Check linter tests (pylint)
        run: PYTHONPATH=src:build/gen python -m pylint tests
      - name: Check linter main (pylint)
        run: PYTHONPATH=src:build/gen python -m pylint main.py
