name: Test Auction Arbitrage Bot

on: [push]

jobs:
  test:
    name: python test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up protobuf
        uses: arduino/setup-protoc@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Compile protobuf
        run: make proto
      - name: Lint
        run: make lint
      - name: Run tests
        run: make test
        
